### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by prosecurity** [lucasfrag/Kali-Linux-Tools-Interface#3]
first of all thanks for this amazing project

i have a small problem after installing it. when  i open the dashboard i dont see anything inside the tool list.

i have also installed the shellinthebox but it says unable to connect

**Comment by lucasfrag** [comment]
Hello Friend!

First of all, thank you very much for the feedback. I was really happy to know that you are enjoying it.

Now, regarding the "bugs":

1) The list of tools will connect to the MySQL database and list the data found. Did you import the bank correctly?

2) The Shell In A Box will be connected to the same host informed when accessing the tool. Let's say you are on localhost:

Access to Shell In A Box will be "https://localhost:4200". If you are accessing the Kali Linux Tools Interface over http, Shell In A Box may not open.

Try to access Shell In A Box at https://localhost:4200 and check if everything is ok with this access. If a browser message appears stating an error in the SSL certificate, it means that you do not have this certificate in your Webservice. Just accept to proceed with the access anyway and everything is fine!

If none of these tips help you in solving the problem, please try to describe in more detail what is going on.

**Comment by prosecurity** [comment]
thanks for the fast response.. 

i have imported the sql file into the kali database you said we should create.

now to use the interface i go to http://localhost/Kali-Linux-Tools-Interface/index.php

and i log in using hostname:localhost
                            user:root
                            password: i use password of my kali system

after login in the interface doesnt show available tools

**Comment by lucasfrag** [comment]
Hello Friend!

Did you make the configuration in the assets/includes/config.php file? In this file, you must enter the data to establish the connection to the MySQL database.

**Comment by lucasfrag** [comment]
Hello Friend.
As I have not received any feedback so far, I am closing this issue.

I hope you are enjoying the tool ;)

See ya!
