### ISSUE TITLE
PDOException

### ISSUE THREAD

**Issue by readshow** [lucasfrag/Kali-Linux-Tools-Interface#4]
[Sun Jul 26 00:01:14.874623 2020] [php7:error] [pid 10474] [client 192.168.0.102:51825] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/html/kaligui/assets/includes/config.php:6\nStack trace:\n#0 /var/www/html/kaligui/assets/includes/config.php(6): PDO->__construct('mysql:host=127....', 'root', 'toor', Array)\n#1 /var/www/html/kaligui/index.php(35): getConnectionDB()\n#2 {main}\n  thrown in /var/www/html/kaligui/assets/includes/config.php on line 6, referer: http://192.168.0.101/kaligui/terminal.php

my config.php 

?php

        // Functions
        function getConnectionDB() {
                $username = "root"; $password = "toor";
                $con = new PDO('mysql:host=127.0.0.1;dbname=kali', $username, $password, array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'utf8'"));
        return $con;
        }

        session_start(); 
         
        // Verifica se existe os dados da sessão de login 
        if (!isset($_SESSION["host"]) || !isset($_SESSION["user"]) || !isset($_SESSION["password"])) { 
                header("Location: login.php"); 
        } else {
                $name = $_SESSION["user"];
                $avatar = "assets/img/profile.jpg";
                $background = "assets/img/background.jpg";
        }

?>

**Comment by lucasfrag** [comment]
Hello Friend!

The error refers to access to MySQL. Is the MySQL database installed? Does the 'kali' database exist? Does the informed user have access to MySQL? Is the password and user correct?

All these data are related to MySQL, ok?

Awaiting return ;)

**Comment by lucasfrag** [comment]
Hello Friend.
As I have not received any feedback so far, I am closing this issue.

I hope you are enjoying the tool ;)

See ya!
